[sql_learning.py:31 -  connect_with_server() ] Connection established successfully.
